from langchain_core.tools import tool
from langchain.agents import create_agent
from src.ultis import get_groq_model, get_system_prompt
# from src.ultis import get_gemini_api, get_system_prompt

from src.tools.Coding_Agent_tools import Code_Generator,Code_Reviewer,Debugger

@tool
def get_code_agents(query: str) -> str:
    """
    Coordinate multiple coding tools to solve software development tasks.

    This tool acts as an orchestrator that routes the user's request to
    specialized agents for code generation, code review, and debugging,
    then returns the final response.

    Args:
        query (str): A programming-related request, code snippet,
            bug report, review request, or development task.

    Returns:
        str: The final response generated by the coding agent,
            which may include generated code, review feedback,
            debugging guidance, or a combination of these.
    """
    coding_agent = create_agent(
        model=get_groq_model(),
        tools=[Code_Generator, Code_Reviewer,Debugger],
        system_prompt=get_system_prompt("testing")
    )
    result = coding_agent.invoke({"messages" : [{"role" :"user", "content":query}]})
    return result["messages"][-1].content