from langchain_core.tools import tool
from langchain.agents import create_agent
from src.ultis import get_groq_model, get_system_prompt
# from src.ultis import get_gemini_api, get_system_prompt
from langchain.agents.middleware import ModelCallLimitMiddleware

from src.tools.Coding_Agent_tools import codegenerator,codereviewer,debugger

@tool
def getcodeagents(query: str) -> str:
    """
    Coordinate multiple coding tools to solve software development tasks.

    This tool acts as an orchestrator that routes the user's request to
    specialized agents for code generation, code review, and debugging,
    then returns the final response.

    Args:
        query (str): A programming-related request, code snippet,
            bug report, review request, or development task.

    Returns:
        str: The final response generated by the coding agent,
            which may include generated code, review feedback,
            debugging guidance, or a combination of these.
    """
    coding_agent = create_agent(
        model=get_groq_model(),
        tools=[codegenerator, codereviewer,debugger],
        system_prompt=get_system_prompt("testing"),
        middleware=[
                 ModelCallLimitMiddleware(
                      thread_limit=10,
                      run_limit=3,
                      exit_behavior="end",
                )
            ]
    )
    result = coding_agent.invoke({"messages" : [{"role" :"user", "content":query}]})
    return result["messages"][-1].content