from langchain_core.tools import tool
from langchain.agents import create_agent
from src.ultis import get_system_prompt, get_model
# from src.ultis import get_gemini_api, get_system_prompt
from langchain.agents.middleware import ModelCallLimitMiddleware, ToolCallLimitMiddleware
from src.memory.store import store
from src.tools.Coding_Agent_tools import codegenerator,codereviewer,debugger
from src.ultis import fallback
@tool("coding_agent")
def getcodeagents(query: str) -> str:
    """
    Coordinate multiple coding tools to solve software development tasks.

    This tool acts as an orchestrator that routes the user's request to
    specialized agents for code generation, code review, and debugging,
    then returns the final response.

    Args:
        query (str): A programming-related request, code snippet,
            bug report, review request, or development task.

    Returns:
        str: The final response generated by the coding agent,
            which may include generated code, review feedback,
            debugging guidance, or a combination of these.
    """
    coding_agent = create_agent(
        model=get_model(),
        tools=[codegenerator, codereviewer,debugger],
        system_prompt=get_system_prompt("Ritik Sontakke"),
        store=store,
        middleware=[
                ModelCallLimitMiddleware(run_limit=5, exit_behavior="end"),
                ToolCallLimitMiddleware(run_limit=10, exit_behavior="end"),
                fallback,
            ]
    )
    result = coding_agent.invoke({"messages" : [{"role" :"user", "content":query}]})
    return result["messages"][-1].content