from langchain_core.tools import tool
from langchain.agents import create_agent
from src.tools.Content_Agent_Tools import blogwriter
from src.tools.Content_Agent_Tools import summarizer
from src.ultis import get_groq_model,get_system_prompt
# from src.ultis import get_gemini_api,get_system_prompt
from langchain.agents.middleware import ModelCallLimitMiddleware


@tool
def getcontentagent(query:str):
    """
    Handle content creation and summarization tasks using specialized writing tools.

    This tool coordinates content-focused agents to generate blog articles,
    summarize text, and assist with general content-writing workflows based
    on the user's request.

    Args:
        query (str): A content-related request such as blog generation,
            article writing, text summarization, or content refinement.

    Returns:
        str: The final content generated by the agent, which may include
            a blog post, summary, or other writing-related output.
    """

    content_agent = create_agent(
        model=get_groq_model(),
        tools=[blogwriter,summarizer],
        system_prompt=get_system_prompt("testing"),
        middleware=[
                 ModelCallLimitMiddleware(
                      thread_limit=10,
                      run_limit=4,
                      exit_behavior="end",
                )
            ]
    )
    result = content_agent.invoke({"messages": [{"role" :"user", "content":query}]})
    return result["messages"][-1].content