from langchain_core.tools import tool
from langchain.agents import create_agent
from src.tools.Content_Agent_Tools import Blog_Writer
from src.tools.Content_Agent_Tools import Summarizer
from src.ultis import get_groq_model,get_system_prompt
# from src.ultis import get_gemini_api,get_system_prompt


@tool
def get_content_agent(query:str):
    """
    Handle content creation and summarization tasks using specialized writing tools.

    This tool coordinates content-focused agents to generate blog articles,
    summarize text, and assist with general content-writing workflows based
    on the user's request.

    Args:
        query (str): A content-related request such as blog generation,
            article writing, text summarization, or content refinement.

    Returns:
        str: The final content generated by the agent, which may include
            a blog post, summary, or other writing-related output.
    """

    content_agent = create_agent(
        model=get_groq_model(),
        tools=[Blog_Writer,Summarizer],
        system_prompt=get_system_prompt("testing")
    )
    result = content_agent.invoke({"messages": [{"role" :"user", "content":query}]})
    return result["messages"][-1].content