from langchain.agents import create_agent
from src.ultis import get_groq_model,get_system_prompt
# from src.ultis import get_gemini_api,get_system_prompt

from src.tools.Web_Research_tools import News_Search,Search_Tool
from langchain_core.tools import tool

@tool
def get_web_agent(query:str)->str:
    """
    Handle web search and news retrieval tasks using specialized search tools.

    This tool coordinates search-focused agents to gather information from
    general web searches and recent news sources, then returns a consolidated
    response based on the user's query.

    Args:
        query (str): A search request, research question, topic of interest,
            or news-related query.

    Returns:
        str: Relevant information, search results, news insights, or a
            synthesized response generated by the web agent.
    """
    web_agent=create_agent(
        model=get_groq_model(),
        tools=[News_Search,Search_Tool],
        system_prompt=get_system_prompt("testing")
    )
    result = web_agent.invoke({"messages": [{"role" : "user", "content" : query}]})
    return result["messages"][-1].content