from langchain.agents import create_agent
from src.ultis import get_groq_model,get_system_prompt, get_openai_model
# from src.ultis import get_gemini_api,get_system_prompt
from langchain.agents.middleware import ModelCallLimitMiddleware, ToolCallLimitMiddleware
from src.tools.Web_Research_tools import newssearch,searchtool
from langchain_core.tools import tool
from src.memory.store import store
@tool
def getwebagent(query:str)->str:
    """
    Handle web search and news retrieval tasks using specialized search tools.

    This tool coordinates search-focused agents to gather information from
    general web searches and recent news sources, then returns a consolidated
    response based on the user's query.

    Args:
        query (str): A search request, research question, topic of interest,
            or news-related query.

    Returns:
        str: Relevant information, search results, news insights, or a
            synthesized response generated by the web agent.
    """
    web_agent=create_agent(
        model=get_openai_model(),
        tools=[newssearch,searchtool],
        system_prompt=get_system_prompt("testing"),
        store=store,
        middleware=[
                ModelCallLimitMiddleware(run_limit=5, exit_behavior="end"),
                ToolCallLimitMiddleware(run_limit=10, exit_behavior="end"),
            ]
    )
    result = web_agent.invoke({"messages": [{"role" : "user", "content" : query}]})
    return result["messages"][-1].content